### ISSUE TITLE
Can't add as custom repo

### ISSUE THREAD

**Issue by a1ee9b** [azogue/fasthue#1]
![grafik](https://user-images.githubusercontent.com/2419211/79663222-1a634b00-81b5-11ea-84d9-cf1f8b0b1d59.png)
When I try to add the provided URL from the README to HACS, Github returns a 404.

Here are my versions:

arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.106-v7
python_version | 3.7.7
timezone | Europe/Berlin
version | 0.108.3
virtualenv | false

**Comment by azogue** [comment]
Hi @a1ee9b, what specific URL did you use? it should be:

**`https://github.com/azogue/fasthue`**

<img width="863" alt="Captura de pantalla 2020-04-19 a las 12 24 47" src="https://user-images.githubusercontent.com/9748301/79685385-cf8b1700-8238-11ea-87d8-c98132573ce2.png">

Could you try again? I just removed and reinstalled it in my production HA and worked ok.

Also, if you used the URL from your screenshot, **from where did you copy it?**

**Comment by azogue** [comment]
Closing this, as now is on https://github.com/hacs/default (and it was also working ok as custom 🤔)
