### ISSUE TITLE
Where to change the polling

### ISSUE THREAD

**Issue by c0nt4x** [azogue/fasthue#11]
Hi

I've installed the integration but the instructions state:

> Add it from the Integrations menu, set the desired new update interval

But where do I set the new interval? Do I have to add code to a .yaml or is there some other way.

Sorry but it's not clear where to set the interval.

**Comment by saaste** [comment]
I wonder if you are having the same [issue](https://github.com/azogue/fasthue/issues/10) I have. Basically, I'm not seeing the configuration UI nor service/sensor that supposed to be there. This also means I can't change the interval.

**Comment by c0nt4x** [comment]
> I wonder if you are having the same [issue](https://github.com/azogue/fasthue/issues/10) I have. Basically, I'm not seeing the configuration UI nor service/sensor that supposed to be there. This also means I can't change the interval.

I found it. After installing fasthue via Hacs then restarted go to HA integrations and add Hue fast polling integration.
