### ISSUE TITLE
No Fast-Hue polling in integrations

### ISSUE THREAD

**Issue by skleenyhoffer** [azogue/fasthue#13]
No Fast-Hue polling in integrations. Followed instructions to the letter. Have directory and files under custom-configuration. Have Fast-Hue polling under Hacs integrations. That's it. Nothing more. Multiple restarts. Nothing. Does this even work anymore or what?

**Comment by skleenyhoffer** [comment]
Started over reinstalling Home Assistant. It worked. No idea what the problem was.

**Comment by Lenny5156** [comment]
I have the same Issue with HA Core 0.118.4, but I don't want to reinstall it. Is there away to solve it?
In my logs I got this entry:

```
Logger: homeassistant.loader
Source: loader.py:465
First occurred: 18:11:41 (1 occurrences)
Last logged: 18:11:41
You are using a custom integration for fasthue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant. 
```
