### ISSUE TITLE
Service fasthue.set_update_interval missing

### ISSUE THREAD

**Issue by huubeikens** [azogue/fasthue#14]
I've installed fasthue using HACS as described in the README.MD. When creating the automation using the automation example the service fasthue.set_update_interval is not known within Home Assistant. Also when calling this service via Developer Tools->Services, a warning is shown that the service cannot be found.

I'm running Hass.io on a raspberry pi 4. System info is as follows:
rch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Amsterdam
version | 0.117.6
virtualenv | false

My log only shows the following:
2020-11-14 03:08:19 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for fasthue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

Please let me know if you need more information.

**Comment by lars-str** [comment]
I had the same problem and probably we missed the same thing: After installing the integration via HACS Store and updating your configuration you also have to add that integration in the GUI. So you have log in to your Home Assistant, go to Settings, click on Integration and then click on the plus icon to add another integration. In the search field, type "hue fast" and you will see the integration to add. Add it and after that the service will be available. It fixed the problem for me :-).

**Comment by skleenyhoffer** [comment]
It doesn't appear under Configuration>Integrations. Hit the + button and it's not there. Installed from HACS and appears under HACS>Integrations but that's it. Can't find an answer as to why or what file to check.

**Comment by huubeikens** [comment]
Thanks! That did the trick. I was new to HACS and thought that adding fasthue to HACS via HACS->Integrations was enough to get it working. But you also need to add fasthue via Configuration->Integrations .

I've modified the README.MD so that this knowlegde is known for all mankind.

**Comment by vylark** [comment]
Hi, just jumping in on this. I have installed it on HACS, restarted HA but when I go to search for it in the Integrations as per the previous response it is only coming up with the official Hue integration. I totally can't work out where I am going wrong with this so if someone was able to give me a hint it would be greatly appreciated

**Comment by ph0b0s101** [comment]
> Hi, just jumping in on this. I have installed it on HACS, restarted HA but when I go to search for it in the Integrations as per the previous response it is only coming up with the official Hue integration. I totally can't work out where I am going wrong with this so if someone was able to give me a hint it would be greatly appreciated

I have the same problem. Have no Idea what to change. Any hints or tipps are much appreciate.
