### ISSUE TITLE
Problems with Polling Sensor

### ISSUE THREAD

**Issue by clipse2004** [azogue/fasthue#23]
Hello everybody,
I can't get any further, I just can't get the sensor to work anymore.
It worked once, suddenly it disappeared and I get the following error message:

Traceback (most recent call last):
  File "/config/custom_components/fasthue/sensor.py", line 42, in async_setup_entry
    device = next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
RuntimeError: coroutine raised StopIteration

I also reinstalled the bridge and Fast Hue, nothing helps. The sensor just doesn't show up anymore!

Can you help?

Merci

**Comment by azogue** [comment]
Hi @clipse2004,

If you are using HA >=2021.6.0, **now the Hue integration has local push communications with the Hue bridge** (see #22), so this custom integration is not necessary anymore, as hue cannot be _faster_ than that :)

You should remove it 👍

**Comment by clipse2004** [comment]
Oh damn, I noticed something new there. However, I did not know that this replaces the pooling :/
And I would like to beat my ears to find the error :D

Thank you!
