### ISSUE TITLE
Setup failed for fasthue error after reboot

### ISSUE THREAD

**Issue by rjmcfadd** [azogue/fasthue#25]
Hello,

I get this error every time I reboot home assistant even though I have removed the fasthue integration. Is there anything else I would need to do to get rid of this error?

Thanks!

`Logger: homeassistant.setup
Source: setup.py:173
First occurred: July 7, 2021, 12:12:57 PM (1 occurrences)
Last logged: July 7, 2021, 12:12:57 PM

Setup failed for fasthue: Integration not found.`

**Comment by azogue** [comment]
> even though I have removed the fasthue integration

That's strange! Are you sure there is no manual YAML config trying to install it? Or maybe you have a corrupted config? 

You could check the content of the file `config/.storage/core.config_entries` and look for an entry with `"domain": "fasthue"` (and remove it manually)
